### ISSUE TITLE
npm, yarn version different

### ISSUE THREAD

**Issue by yesseecity** [HPouyanmehr/mui-markdown#10]
npm is 1.0.1   https://www.npmjs.com/package/mui-markdown
yarn is 0.5.6  https://yarnpkg.com/package/mui-markdown

**Comment by HPouyanmehr** [comment]
Hey @yesseecity,
I don't publish the package directly on yarn, but yarn uses the same registry as npm, so any package that is published on npm should be available on yarn as well. You see the 0.5.6 version on yarn because it caches the package metadata, and the 0.5.6 has more downloads on npm than the latest version right now. 

By running the `yarn add mui-markdown` you should be able to add the latest version, however, if the cached one is installed you can try `yarn cache clean` first to force it to fetch the latest version.

It's not an issue with the package itself. You can see the same thing for other packages like `@mui/material`.
