### ISSUE TITLE
JoyUI Support

### ISSUE THREAD

**Issue by boredmage** [HPouyanmehr/mui-markdown#15]
**Is your feature request related to a problem? Please describe.**
It would be great If I can use JoyUI instead of Material UI

**Describe the solution you'd like**
To be able to use JoyUI stayles rather

**Describe alternatives you've considered**
Modifying the node_modules, so I need to find some other ways.

**Additional context**
Joy UI default sizes looks different and it wouldn't be nice writing different `overrides ` to get that done.

<img width="1512" alt="Screenshot 2023-08-09 at 14 44 36" src="https://github.com/HPouyanmehr/mui-markdown/assets/51055890/f6093842-df05-4b39-a8ab-df814c069b8c">

**Comment by HPouyanmehr** [comment]
Hey @Qudusayo,
Thanks for suggesting this. Generally, your request about using the joy-ui instead of mui seems helpful. However, I need some free time to analyze and check the possible solutions to add an option to use joy instead of material (Like the syntax highlighter that is optional now).

They're both using emotion as the engine for styling, and I think it can be implemented with no conflicts or side effects (The overall package size will be affected).

**Comment by bgaurav7** [comment]
@Qudusayo I have created a port for JoyUI 

[Github](https://github.com/bgaurav7/joyui-markdown)
[npmjs](https://www.npmjs.com/package/joyui-markdown)

**Comment by HPouyanmehr** [comment]
Hey @Qudusayo 

As @bgaurav7 changes (#20) had conflicts for MUI users, I created a [new repository](https://github.com/HPouyanmehr/jui-markdown) and published the Joy UI alternative for this package. The package is available on [NPM](https://www.npmjs.com/package/jui-markdown) as `jui-markdown` (Joy UI Markdown).
