### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by WardenCommander** [HPouyanmehr/mui-markdown#2]
**Describe the bug**
I tried your .md file but i get following error.

wait  - compiling /blog/app (client and server)...
error - ./pages/blog/myMarkdown.md
Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
| name: Bug report
| about: Create a report to help us improve

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HPouyanmehr** [comment]
Hi,
mui-markdown helps you render the markdown file data with MUI components (**not loading the markdown file itself**). Your issue is about loading .md files, and you need to install a package for that and config webpack to load markdown files properly. Some libraries do this for you like [remark-loader](https://github.com/webpack-contrib/remark-loader). As this is not a mui-markdown issue i'll close this.
